### ISSUE TITLE
Version 1.0 and greater broken on NRF52 feather board (with VEML7700)

### ISSUE THREAD

**Issue by wb8wka** [adafruit/Adafruit_BusIO#1]
Version 0.3 and below compiles fine.  See error messages below

-----

Build options changed, rebuilding all
In file included from C:\Users\kingr\Google Drive\Arduino\libraries\Adafruit_BusIO/Adafruit_SPIDevice.h:1:0,

                 from C:\Users\kingr\Google Drive\Arduino\libraries\Adafruit_BusIO/Adafruit_BusIO_Register.h:2,

                 from C:\Users\kingr\Google Drive\Arduino\libraries\Adafruit_BusIO/Adafruit_I2CRegister.h:1,

                 from C:\Users\kingr\Google Drive\Arduino\libraries\Adafruit_VEML7700_Library/Adafruit_VEML7700.h:23,

                 from C:\Users\kingr\Google Drive\Arduino\libraries\Adafruit_VEML7700_Library\examples\veml7700_test\veml7700_test.ino:1:

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h: In static member function 'static byte SPIClass::transfer(byte)':

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:56:3: error: 'SPDR' was not declared in this scope

   SPDR = _data;

   ^~~~

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:56:3: note: suggested alternative: 'SPI'

   SPDR = _data;

   ^~~~

   SPI

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:57:12: error: 'SPSR' was not declared in this scope

   while (!(SPSR & _BV(SPIF)))

            ^~~~

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:57:12: note: suggested alternative: 'SPI'

   while (!(SPSR & _BV(SPIF)))

            ^~~~

            SPI

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:57:23: error: 'SPIF' was not declared in this scope

   while (!(SPSR & _BV(SPIF)))

                       ^~~~

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:57:23: note: suggested alternative: 'SPI'

   while (!(SPSR & _BV(SPIF)))

                       ^~~~

                       SPI

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:57:19: error: '_BV' was not declared in this scope

   while (!(SPSR & _BV(SPIF)))

                   ^~~

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:57:19: note: suggested alternative: '_B'

   while (!(SPSR & _BV(SPIF)))

                   ^~~

                   _B

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h: In static member function 'static void SPIClass::attachInterrupt()':

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:63:3: error: 'SPCR' was not declared in this scope

   SPCR |= _BV(SPIE);

   ^~~~

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:63:3: note: suggested alternative: 'SPI'

   SPCR |= _BV(SPIE);

   ^~~~

   SPI

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:63:15: error: 'SPIE' was not declared in this scope

   SPCR |= _BV(SPIE);

               ^~~~

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:63:15: note: suggested alternative: 'SPI'

   SPCR |= _BV(SPIE);

               ^~~~

               SPI

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:63:11: error: '_BV' was not declared in this scope

   SPCR |= _BV(SPIE);

           ^~~

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:63:11: note: suggested alternative: '_B'

   SPCR |= _BV(SPIE);

           ^~~

           _B

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h: In static member function 'static void SPIClass::detachInterrupt()':

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:67:3: error: 'SPCR' was not declared in this scope

   SPCR &= ~_BV(SPIE);

   ^~~~

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:67:3: note: suggested alternative: 'SPI'

   SPCR &= ~_BV(SPIE);

   ^~~~

   SPI

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:67:16: error: 'SPIE' was not declared in this scope

   SPCR &= ~_BV(SPIE);

                ^~~~

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:67:16: note: suggested alternative: 'SPI'

   SPCR &= ~_BV(SPIE);

                ^~~~

                SPI

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:67:12: error: '_BV' was not declared in this scope

   SPCR &= ~_BV(SPIE);

            ^~~

C:\Users\kingr\Google Drive\Arduino\libraries\SPI/SPI.h:67:12: note: suggested alternative: '_B'

   SPCR &= ~_BV(SPIE);

            ^~~

            _B

In file included from C:\Users\kingr\Google Drive\Arduino\libraries\Adafruit_BusIO/Adafruit_BusIO_Register.h:2:0,

                 from C:\Users\kingr\Google Drive\Arduino\libraries\Adafruit_BusIO/Adafruit_I2CRegister.h:1,

                 from C:\Users\kingr\Google Drive\Arduino\libraries\Adafruit_VEML7700_Library/Adafruit_VEML7700.h:23,

                 from C:\Users\kingr\Google Drive\Arduino\libraries\Adafruit_VEML7700_Library\examples\veml7700_test\veml7700_test.ino:1:

C:\Users\kingr\Google Drive\Arduino\libraries\Adafruit_BusIO/Adafruit_SPIDevice.h: At global scope:

C:\Users\kingr\Google Drive\Arduino\libraries\Adafruit_BusIO/Adafruit_SPIDevice.h:27:3: error: 'SPISettings' does not name a type

   SPISettings *_spiSetting;

   ^~~~~~~~~~~

Multiple libraries were found for "SPI.h"
 Used: C:\Users\kingr\Google Drive\Arduino\libraries\SPI
 Not used: C:\Users\kingr\AppData\Local\Arduino15\packages\adafruit\hardware\nrf52\0.11.0\libraries\SPI
exit status 1
Error compiling for board Adafruit Bluefruit Feather nRF52832.

**Comment by ladyada** [comment]
```Multiple libraries were found for "SPI.h"
Used: C:\Users\kingr\Google Drive\Arduino\libraries\SPI
Not used: C:\Users\kingr\AppData\Local\Arduino15\packages\adafruit\hardware\nrf52\0.11.0\libraries\SPI
exit status 1```
you are doing something really weird with the SPI lib having it in multiple locations. dont do that. delete the one in your google drive
