### ISSUE TITLE
Library doesn't work for ESP32 or ESP8266 on PlatformIO

### ISSUE THREAD

**Issue by WackoKacko** [adafruit/Adafruit_BusIO#118]
Adafruit_BusIO causes the build to fail for the following reason:

_#include <SPI.h>
^~~
compilation terminated.
*** [.pio\build\d1_mini\lib90c\Adafruit BMP280 Library\Adafruit_BMP280.cpp.o] Error 1_

Is there any easy fix?

**Comment by msrba** [comment]
I have the same issue, is there any solution?

**Comment by ladyada** [comment]
there is something wrong with platformio - SPI.h is native SPI hardware library and comes wih the board support package!
