### ISSUE TITLE
Arduino 101 SPI_BITORDER_MSBFIRST error

### ISSUE THREAD

**Issue by xaniat** [adafruit/Adafruit_BusIO#13]
- Arduino board:  Arduino 101
- Arduino IDE version:  Arduino 1.6.9
- List the steps to reproduce the problem below: Compiled basic_readings example from the Adafruit MPU6050 library.

I get two errors when I compile it: 
..\Arduino\libraries\Adafruit_BusIO/Adafruit_SPIDevice.h:37:43: error: could not convert 'SPI_BITORDER_MSBFIRST' from '_BitOrder' to 'BitOrder'

                      BitOrder dataOrder = SPI_BITORDER_MSBFIRST,

                                           ^

...\Arduino\libraries\Adafruit_BusIO/Adafruit_SPIDevice.h:42:43: error: could not convert 'SPI_BITORDER_MSBFIRST' from '_BitOrder' to 'BitOrder'

                      BitOrder dataOrder = SPI_BITORDER_MSBFIRST,

Could you please fix this?

Thanks.

**Comment by ladyada** [comment]
hi we looked and it doesnt not seem possible - arc32 has both numeric and enum versions of MSBFIRST - please use another library :) the arduino 101 is discontinued
