### ISSUE TITLE
Side effect with hardware SPI causes pin 10 to be high after begin(), regardless of _cs value

### ISSUE THREAD

**Issue by dsball** [adafruit/Adafruit_BusIO#22]
- Arduino board:  Uno

- Arduino IDE version (found in Arduino -> About Arduino menu):  VS Code/PlatformIO

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): Call to _spi->begin() at Adafruit_SPIDevice.cpp:67 causes SS (pin 10) to be set HIGH in the arduino library, regardless of the value of _cs. I suggest storing the current pin mode and output state of pin 10 and restoring after the call.

**Comment by ladyada** [comment]
hi, that is done within the Arduino core, not here. and SS must be set to an output on Uno for SPI to work as master, so undoing that would cause more confusion. if you really have a problem with SS being set to an output you can take it up with arduino here :)
https://github.com/arduino/ArduinoCore-avr/blob/master/libraries/SPI/src/SPI.cpp#L31
