### ISSUE TITLE
delay() in write_then_read needed?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_BusIO#24]
Is this hard wired delay in `write_then_read()` required for all use cases?
https://github.com/adafruit/Adafruit_BusIO/blob/256edbe33372dcb57f497dde75e6e5494db156bb/Adafruit_SPIDevice.cpp#L304

**Comment by ladyada** [comment]
no, odd please remove it

**Comment by caternuson** [comment]
Fixed with #25
