### ISSUE TITLE
Missing spi_readwrite example

### ISSUE THREAD

**Issue by AnHardt** [adafruit/Adafruit_BusIO#3]
https://github.com/adafruit/Adafruit_BusIO/blob/master/examples/spi_readwrite/i2c_readwrite.ino

seems to be the same as 

https://github.com/adafruit/Adafruit_BusIO/blob/master/examples/i2c_readwrite/i2c_readwrite.ino

**Comment by ladyada** [comment]
fixe din https://github.com/adafruit/Adafruit_BusIO/commit/85577e9f2ef71fd05245041c6e5698023f708855
