### ISSUE TITLE
Support for bit tranfers....

### ISSUE THREAD

**Issue by jbuszkie** [adafruit/Adafruit_BusIO#42]
Is there a way to specify an arbitrary number of bits to transfer via SPI?  I have a device that's interface is very SPI-like.  But it expects 3bits of command followed by 6 bits of address followed by 8bits of data.  But from the code here..(at least the bit banged part) it looks like it sends just 8 bit package.. My guess is I'll have to bit bang this myself...

**Comment by ladyada** [comment]
you'll have to bitbang it!
