### ISSUE TITLE
Add check for I2C pull ups?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_BusIO#44]
Any way we could protect against nothing being connected to the bus? This currently leads to code locking up. Here's a simple example:
```cpp
#include <Adafruit_I2CDevice.h>

#define ADDRESS 0x42

void setup() {
  Serial.begin(9600);
  while(!Serial);
  Serial.println("I2C TEST");

  Serial.println("Create.");
  Adafruit_I2CDevice *i2c_dev = new Adafruit_I2CDevice(ADDRESS, &Wire);

  Serial.println("Begin.");
  i2c_dev->begin();

  Serial.println("Write.");
  uint8_t buffer[1];
  buffer[0] = ADDRESS;
  i2c_dev->write(buffer, 1);

  Serial.println("Done.");
}

void loop() {
}
```

With pull ups connected, it gets through the code:
![Screenshot from 2021-04-01 13-27-20](https://user-images.githubusercontent.com/8755041/113350472-5f14c300-92ee-11eb-91b0-60a1a9e6cc17.png)

But **without** pull ups, it locks up:
![Screenshot from 2021-04-01 13-26-49](https://user-images.githubusercontent.com/8755041/113350461-5ae8a580-92ee-11eb-9459-bca8f6f3c39d.png)

This should really be something that Wire takes care of. But that's probably not a viable option.

Here's how CP does it for ref:
https://github.com/adafruit/circuitpython/blob/main/ports/atmel-samd/common-hal/busio/I2C.c#L79

**Comment by ladyada** [comment]
oof
not really because we dont know what pins are being used for Wire...

**Comment by caternuson** [comment]
:( good point....so probably not much that can be done, other than "if code locks up, check wiring".

This relates to this for more context:
https://github.com/adafruit/Adafruit_ADS1X15/issues/64

And just to illustrate the issue more lower level. Here's same thing just using Wire directly:
```cpp
#include <Wire.h>

#define ADDRESS 0x42

void setup() {
  Serial.begin(9600);
  while(!Serial);
  Serial.println("I2C TEST");

  Serial.println("Create.");
  TwoWire *theWire = &Wire;

  Serial.println("Begin.");
  theWire->begin();

  Serial.println("Write.");
  uint8_t buffer[1];
  buffer[0] = ADDRESS;
  theWire->beginTransmission(ADDRESS);
  theWire->write(buffer, 1);
  theWire->endTransmission();

  Serial.println("Done.");
}

void loop() {
}
```

**With pull ups:**
![Screenshot from 2021-04-01 14-21-47](https://user-images.githubusercontent.com/8755041/113355615-e6196980-92f5-11eb-9595-860e3f8a2ffe.png)


**Without pull ups:**
![Screenshot from 2021-04-01 14-22-09](https://user-images.githubusercontent.com/8755041/113355619-e9acf080-92f5-11eb-8783-0e1e2d7d8cd1.png)

**Comment by ladyada** [comment]
yeah basically - its part of why we added it to Circuit Python. in Arduino there's just no access to that information

**Comment by caternuson** [comment]
ok, gonna close this then. good to at least have something to point to for when this comes up.
