### ISSUE TITLE
Chunkify I2C?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_BusIO#58]
Have recently run into several libraries that have created their own internal chunkification of I2C writes if the outbound buffer exceeds the max buffer size for the target platform. That buffer size information is being provided by this library, via `maxBufferSize()`. Would it make sense to implement chunkification here in this library?

Same question for reads, although the libraries cited above were not doing that.

**Comment by ladyada** [comment]
letz chunkz!

**Comment by caternuson** [comment]
**hopefully** done with #59
:crossed_fingers:  :crossed_fingers:  :crossed_fingers:  :crossed_fingers:
