### ISSUE TITLE
BitOrder enum conflicts with megaAVR boards

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_BusIO#6]
The ones that show up under Tools -> Boards -> Arduino megaAVR Boards. 

Re:
https://forums.adafruit.com/viewtopic.php?f=19&t=158099

Guessing this just needs some tweaks to the preprocessor logic?

**Comment by ladyada** [comment]
added in 1.09

**Comment by caternuson** [comment]
woosh! awesome. thanks!
