### ISSUE TITLE
Chunks not working on ESP32

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_BusIO#64]
Related:
https://forums.adafruit.com/viewtopic.php?f=25&t=183433

Recreated using [pixels_test](https://github.com/adafruit/Adafruit_AMG88xx/blob/master/examples/pixels_test/pixels_test.ino) example from AMG88xx library.

![Screenshot from 2021-09-24 12-42-17](https://user-images.githubusercontent.com/8755041/134731491-9dfda033-5e8e-4053-860f-4218565ce7ca.png)

Seems related to usage of `stop` parameter here:
https://github.com/adafruit/Adafruit_BusIO/blob/b903c7e0154cfe20ea618f972fad3277feae6fb2/Adafruit_I2CDevice.cpp#L179
which was not in previous chunk code:
https://github.com/adafruit/Adafruit_AMG88xx/blob/90e9eea8c43b6a173f10029029cec85ab1818823/Adafruit_AMG88xx.cpp#L234

**Comment by ladyada** [comment]
erm, should probably pass `stop` thru there yeah?

**Comment by caternuson** [comment]
It's passing through to the actual read start here:
https://github.com/adafruit/Adafruit_BusIO/blob/b903c7e0154cfe20ea618f972fad3277feae6fb2/Adafruit_I2CDevice.cpp#L193

But seems to be more fundamentally broken. Better example. Using a Feather ESP32. Nothing fancy, just try a read of 32 bytes:
```cpp
#include <Wire.h>

#define WIRE Wire
#define I2C_ADDRESS (0x69)
#define READ_SIZE (32)

void setup() {
  Serial.begin(9600);
  while(!Serial);

  uint8_t buffer[READ_SIZE];
  
  WIRE.begin();
  WIRE.requestFrom(I2C_ADDRESS, 32, true);
  uint32_t count = 0;
  while (WIRE.available() and count < READ_SIZE) {
    buffer[count++] = WIRE.read();
  }
}

void loop() {
}
```

Generates expected traffic:
![screenshot](https://user-images.githubusercontent.com/8755041/134733469-d6070363-7e36-4716-ac32-595104f6b438.png)

Change:
```cpp
  WIRE.requestFrom(I2C_ADDRESS, 32, true);
```
to:
```cpp
  WIRE.requestFrom(I2C_ADDRESS, 32, false);
```
and nothing happens on the bus.

**Comment by ladyada** [comment]
try using something else, esp 2.0.0 broke a ton of stuff

**Comment by caternuson** [comment]
Just to document behavior on a different platform - **Qt Py M0**

**stop = true**
![qtpy_m0_true](https://user-images.githubusercontent.com/8755041/134734491-be80698f-f6fb-4229-8c04-011f8a9bec6d.png)

**stop = false**
![qtpy_m0_false](https://user-images.githubusercontent.com/8755041/134734505-0ce4e02b-f9bc-4a78-b77e-eb776707277c.png)

**Comment by ladyada** [comment]
k, looks right to me, there's a stop in the first one, none in the second

**Comment by caternuson** [comment]
Yep. Just documenting expected behavior. Qt Py works as expected.

Just tried with ESP32 BSP 1.0.6 and same results as with BSP 2.0.0.

**Comment by ladyada** [comment]
yah ok try 
https://github.com/espressif/arduino-esp32/issues/4729#issuecomment-922737664

**Comment by caternuson** [comment]
hey! i know that pr :)
https://github.com/espressif/arduino-esp32/issues/5470#issuecomment-922738896

it does something different, but not the expected. basically same behavior either way.

**stop = true**
![feather_esp32_pr5683_true](https://user-images.githubusercontent.com/8755041/134736465-9000ccfb-660c-4745-8d14-b5f0138bc4ea.png)

**stop = false**
![feather_esp32_pr5683_false](https://user-images.githubusercontent.com/8755041/134736512-786b40a1-816e-4454-ad5d-6e9647ae5497.png)

**Comment by ladyada** [comment]
ok please reply to that PR with the deets of what isnt workin

**Comment by caternuson** [comment]
Closing. For now at least. The base issue for this is in the ESP32 BSP and, per comment here:
https://github.com/espressif/arduino-esp32/issues/5702#issuecomment-1111414087
can not be supported for ESP32.
