### ISSUE TITLE
BusIO Omits OneWire Class

### ISSUE THREAD

**Issue by etherfi** [adafruit/Adafruit_BusIO#9]
In native CircuitPython, this module possess an additional class, the OneWire class. It is missing here, meaning examples like this one don't work:

https://learn.adafruit.com/using-ds18b20-temperature-sensor-with-circuitpython/circuitpython

Please add the missing class!

FYI, I'm trying to use OneWire with the Adafruit FT232H module.

**Comment by ladyada** [comment]
hi - this library is for arduino not circuitpython and you can't use the FT232h with this library. are you asking to add 1wire to blinka?
