### ISSUE TITLE
issue with compiling the program to ESP8266

### ISSUE THREAD

**Issue by alsurya** [adafruit/Adafruit_BusIO#99]
Hi Guys, I have a problem with compiling the program to Board ESP8266, 

when I use this code _Wire.begin(sda,scl);_ but that error was not in this scope and then I tried to change code like a _Wire.begin(4,5);_ when I verified the code has an error, pls see below the message error 

C:\Users\lapto\Documents\Arduino\libraries\Adafruit_BusIO\Adafruit_SPIDevice.cpp: In member function 'void Adafruit_SPIDevice::transfer(uint8_t*, size_t)':
C:\Users\lapto\Documents\Arduino\libraries\Adafruit_BusIO\Adafruit_SPIDevice.cpp:137:31: error: no matching function for call to 'SPIClass::transfer(uint8_t*&, size_t&)'
     _spi->transfer(buffer, len);
                               ^
C:\Users\lapto\Documents\Arduino\libraries\Adafruit_BusIO\Adafruit_SPIDevice.cpp:137:31: note: candidate is:
In file included from C:\Users\lapto\Documents\Arduino\libraries\Adafruit_BusIO\Adafruit_SPIDevice.h:9:0,
                 from C:\Users\lapto\Documents\Arduino\libraries\Adafruit_BusIO\Adafruit_SPIDevice.cpp:1:
C:\Users\lapto\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\libraries\SPI/SPI.h:65:11: note: uint8_t SPIClass::transfer(uint8_t)
   uint8_t transfer(uint8_t data);
           ^
C:\Users\lapto\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\libraries\SPI/SPI.h:65:11: note:   candidate expects 1 argument, 2 provided
exit status 1
Error compiling for board Generic ESP8266 Module.

- Arduino board:  **ESP8266**

- Arduino IDE version (1.8.19):

**Comment by ladyada** [comment]
the code compiles on esp8266 using latest board support package:
https://github.com/adafruit/Adafruit_BusIO/runs/7057533716?check_suite_focus=true#step:8:459
to change i2c pins, use setPins()
https://github.com/espressif/arduino-esp32/issues/3779
it exists in esp32 and probably in 8266 as well - if not, please open an issue with espressif to add setPins for 8266! :)
